pub mod classification;
#[path = "duplicate-review.rs"]
pub mod duplicate_review;
pub mod duplicates;
pub mod files;
pub mod folders;
pub mod inbox;
pub mod metadata;
pub mod organizer;
pub mod rename;
pub mod workspace;
